# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
x=np.zeros((10))
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
y=np.arange(10,49)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [4]:
y.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
y.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:

np.version.version

np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sabee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sabee/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sabee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sabee/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sabee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sabee/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/sabee/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/sabee/anaconda3\\Library\\include']


7. Print the dimension of the array in question 3


In [7]:
y.ndim

1

8. Create a boolean array with all the True values

In [8]:
y=np.ones(10,dtype=bool)
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
y=np.ones((3,3))
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

10. Create a three dimensional array



In [10]:
y=np.ones((3,3,3))
y

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
x=np.array([1,2,3,4,5])
x=np.flipud(x)
x

array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
x=np.zeros((10))
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
x=np.zeros((3,3))
x[0,0]=1
x[1,1]=1
x[2,2]=1
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1=np.array([[1.,2.,3.,],[4.,5.,6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=np.where(arr1>=arr2,arr1+arr2,arr1-arr2)
arr

array([[ 1., -2.,  4.],
       [-3.,  7., -6.]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr=np.arange(10)
arr1=arr[1:10:2]
arr1


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr=np.arange(10)
arr[1:10:2]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr=np.arange(10)
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
arr=np.ones((5,5))
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d = np.where(arr2d==5,12,arr2d)
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0:-1] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr[0][0]        



1

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [40]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr[1][1]

5

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr[0:2,2]

array([3, 6])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [43]:
arr=np.random.rand(10,10)

a=np.amax(arr)
b=np.amin(arr)
c=[a,b]
c

[0.9935934131001767, 0.0005153886897323323]

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr=a==b
arr

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr1=np.where(a==b)
arr1



(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
arr = np.where(names=='Will')
arr1=np.where(data[arr])
arr1




(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [30]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
arr = np.where(names!='Will')
arr1 = np.where(names!='Joe')

a = np.where(data[arr]) and np.where(data[arr1])
a

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3], dtype=int64),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [31]:
arr=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.],[13.,14.,15.]])
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.],
       [13., 14., 15.]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [32]:

arr= np.array([[[1.0,2.0,3.0,4.0],[5., 6., 7., 8.]],[[9., 10., 11., 12.],[13., 14., 15., 15.9]]])
arr
np.shape(arr)



(2, 2, 4)

33. Swap axes of the array you created in Question 32

In [33]:
arr = np.transpose(arr)
arr

array([[[ 1. ,  9. ],
        [ 5. , 13. ]],

       [[ 2. , 10. ],
        [ 6. , 14. ]],

       [[ 3. , 11. ],
        [ 7. , 15. ]],

       [[ 4. , 12. ],
        [ 8. , 15.9]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [34]:
arr = np.array([1,2,0.1,0.3,10,0.001,4,6,1.9,9])
arr = np.sqrt(arr)
arr1 = np.where(arr<0.500,0,arr)
arr1

array([1.        , 1.41421356, 0.        , 0.54772256, 3.16227766,
       0.        , 2.        , 2.44948974, 1.37840488, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [35]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
arr = np.where(arr1>arr2,arr1,arr2)
arr

array([ 1.56614044,  1.39081519,  1.8516331 , -0.15956747, -1.12712162,
        0.07462154,  1.05336454, -0.04787281,  0.2995827 , -0.07366993,
        1.32094018,  2.24185517])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [36]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
arr = np.unique(names)
arr1 = np.sort(arr)
arr1

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [37]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
sampleArray[1]
sampleArray = np.where(sampleArray==sampleArray[1],newColumn,sampleArray)
sampleArray

array([[34, 43, 73],
       [10, 10, 10],
       [53, 94, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [38]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z = np.dot(x,y)
z

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [39]:
arr = np.random.randn(20)
arr1=np.cumsum(arr)
arr1

array([-0.03255211, -0.06453549,  0.81258011, -0.31568507,  0.98216287,
       -0.8984091 , -1.05231891, -1.80918558, -2.65674123, -1.86527853,
       -1.45835337, -0.13711824,  0.64224461,  2.00043118,  0.93693172,
       -0.30400242, -0.26880096, -0.22592693,  1.13075879,  1.0012865 ])